FROM milvusbootcamp/img-search-client:assets-1.1 AS Assets

FROM nginx:1.23.1-alpine
RUN rm -rf /etc/nginx/conf.d
COPY docker/nginx/conf /etc/nginx
COPY --from=Assets /assets /usr/share/nginx/html/
EXPOSE 80
WORKDIR /usr/share/nginx/html
COPY ./env.sh .
COPY .env .
RUN apk add --no-cache bash
RUN chmod +x env.sh
CMD ["/bin/bash", "-c", "/usr/share/nginx/html/env.sh && nginx -g \"daemon off;\""]