FROM milvusbootcamp/img-search-client:assets-1.1 AS Assets
FROM golang:1.19.0-alpine3.16 AS GoBuilder
RUN apk add git bash gcc musl-dev upx
WORKDIR /app
COPY --from=Assets /assets      /app/assets
COPY docker/standalone/*  ./
ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOPROXY=https://goproxy.cn
RUN go build -ldflags "-w -s" -o web main.go && \
    upx -9 -o web.minify web

FROM "alpine:3.16.0"
COPY --from=GoBuilder /app/web.minify /bin/web
EXPOSE 80
CMD ["web"]