version: "2.3"
services:
    milvus-mysql:
      restart: always
      image: mysql:5.7
      volumes:
        - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        - ./metadata:/var/lib/mysql
      ports:
        - "0.0.0.0:3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 'milvusroot'
        MYSQL_DATABASE: 'milvus'
      healthcheck:
        test: ["CMD", "sleep", "5"]
        interval: 1s
        timeout: 10s
        retries: 2

