version: '3'
services:
  web-client:
    image: chenglong555/pic_search_demo_web:0.2.0
    ports:
      - "8001:80"
    environment:
      - MILVUS_HOST=192.168.1.8
    networks:
      - app
    depends_on:
      - web-server
  web-server:
    image: pic-demo:v2
    ports:
      - "35000:5000"
    volumes:
      - /home/lcl/workspace/poc/uzhujia_test/kitchen:/tmp/pic1
    environment:
      - MILVUS_HOST=192.168.1.8
      - DATA_PATH=/tmp/images-data
    networks:
      - app
networks:
  app:
    driver: bridge
